# version: '3'

# services:
#   db:
#     image: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: goods
#     ports:
#       - '3306:3306'

#   app:
#     build: .
#     ports:
#       - '3000:3000'
#     depends_on:
#       - db
#     environment:
#       DATABASE_HOST: db
#       DATABASE_PORT: 3306
#       DATABASE_USERNAME: root
#       DATABASE_PASSWORD: root
#       DATABASE_NAME: goods

version: '3.8'

services:
  app:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    container_name: db
    environment:
      MYSQL_HOST: database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goods
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - nesjs-network

networks:
  nesjs-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
